# Generated by Django 5.1.4 on 2025-01-28 16:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('rial_balance', models.DecimalField(decimal_places=2, default=0, help_text='total cash', max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_balance', models.DecimalField(decimal_places=6, default=0, help_text='total gold', max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('-create_time',),
                'get_latest_by': ('create_time',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('transaction_type', models.CharField(choices=[('INCREASE_CREDIT', 'increase credit'), ('SELL', 'sell'), ('BUY', 'buy')], max_length=15)),
                ('rial_amount', models.DecimalField(decimal_places=2, default=0, help_text='rial', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_amount', models.DecimalField(decimal_places=6, default=0, help_text='gerame tala', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-create_time',),
                'get_latest_by': ('create_time',),
                'abstract': False,
            },
        ),
    ]
