# Generated by Django 5.1.4 on 2025-01-28 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, help_text='price of gold per gram at transaction time', max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', help_text='status of the transaction', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rial_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='rial', max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
