# Generated by Django 5.1.4 on 2025-01-28 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_price_per_gram_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessasset',
            name='rial_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='total cash', max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rial_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='rial', max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
